### PR TITLE
Version List parsed as Json

### PR DESCRIPTION
**Pull request by YCCertifai**
# Description

### 1. Parsing annotation with json instead of string 
same logic as #351, with "file_size" param included and also rename "anno_data" -> "annotation_data"

image

### 2. Latest frontend code included

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Tested on?

- [ ] Windows  
- [x] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Comment by codenamewei** [comment]
@YCCertifai can you check if refresh button and import button is working in your branch?

also check if checksum field in the json if its null  (which not supposed to)

**Review by codenamewei — CHANGES_REQUESTED** [review]
Tried on mac. Import project not working fine. 

How to reproduce
1. create a project, choose a project folder with a few images inside, load the project
2. put more images in the project folder, refresh 
3. export config file
4. reimport as new project (new images put in the project folder after refresh not shown in thumbnail)
@YCCertifai

**Comment by YCCertifai** [comment]
> Tried on mac. Import project not working fine.
> 
> How to reproduce
> 
> 1. create a project, choose a project folder with a few images inside, load the project
> 2. put more images in the project folder, refresh
> 3. export config file
> 4. reimport as new project (new images put in the project folder after refresh not shown in thumbnail)
>    @YCCertifai

@codenamewei bug fixed.

**Review by codenamewei — APPROVED** [review]
👍

**Pull request merged**
