### PR TITLE
🚀 Release alpha2

### PR DESCRIPTION
**Pull request by devenyantis**
# Description

Alpha2 release.

In this PR, 
- CHANGELOG updated
- gitbook docs - https://docs.classifai.ai/
- Release page draft - https://github.com/CertifaiAI/classifai/releases/tag/untagged-f1bfe807929e3bd1b5e0

We still don't have Mac installer for now.

Will publish the draft once merged.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (Non-breaking change which fixes an issue)
- [ ] New feature (Non-breaking change which adds functionality)
- [ ] Breaking change (Fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update (Example: REST API changes)

# Tested on?

- [ ] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged
- [ ] CHANGELOG.md has been updated
- [ ] Update [Gitbook REST API Page](https://docs.classifai.ai/v/dev/development/rest-api)

### CODE REVIEW

**Review by codenamewei — APPROVED** [review]
look great....all are covered from the look of it.

@devenyantis 
Reminder on
distribution link in readme and docs.classifai.ai
is created with bit.ly (by kenge using specific account) to track the demographics of downloads of each package.

For release tag, we included the raw distribution 
(The assumption is normally people will not know/use that spot to download)

**Comment by devenyantis** [comment]
> @devenyantis
> Reminder on
> distribution link in readme and docs.classifai.ai
> is created with bit.ly (by kenge using specific account) to track the demographics of downloads of each package.
> 
> For release tag, we included the raw distribution
> (The assumption is normally people will not know/use here to download)

Ahh. Forgot. Thanks

**Review by yipkhenlai — APPROVED** [review]

**Comment by devenyantis** [comment]
@codenamewei 

Deleting Installation for mac guide for now. Will add it back once we have the installer.

**Review by hansheng0512 — APPROVED** [review]

**Review by yinchuangsum — APPROVED** [review]

**Review by yinchuangsum — CHANGES_REQUESTED** [review]
image
https://github.com/CertifaiAI/classifai/blame/v2_alpha/readme.md#L153-L156
you might want to change the download link in the readme page too

**Review by codenamewei — APPROVED** [review]

**Review by yinchuangsum — APPROVED** [review]

**Review by amalsyahmi — APPROVED** [review]

**Pull request merged**
