### PR TITLE
Bug fix folder and file validation [WIP]

### PR DESCRIPTION
**Pull request by YCCertifai**
# Description
### Folder validation
To fix bug #393.
**If root path is missing:**
1. Will have a log message about the root path is missing.
image
2. The project will still be visible, but the total number of images is 0. Letting the project stays visible will prevent duplication of project naming.
image

**If root path is restored:**
1. Images will be restored by refreshing the browser.
image

**Extra to have?[Not Implemented Yet]**
Change the project status, for example to [Project Path Missing] to be more descriptive. **Requires frontend support**
image

### Image validation
To fix bug #395 
**Changes the method used to calculate the total number of images in folder**
**from** https://github.com/CertifaiAI/classifai/blob/v2_alpha/classifai-core/src/main/java/ai/classifai/util/data/FileHandler.java#L69-L83
**to** https://github.com/CertifaiAI/classifai/blob/sum_v2a_folderFileValidation/classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java#L252-L255.

**Better logging for not supported image**
Types of files are recorded in the log.
image

### Changelog
- Not related to this pr as these are fixes for developing features.
- Added for auto pr for frontend

Fixes # (issue)
#393 
#395 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Tested on?

- [ ] Windows  
- [x] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged
- [x] CHANGELOG.md has been updated.

### CODE REVIEW

**Review by devenyantis — APPROVED** [review]
Tested on windows.

**Review by codenamewei — CHANGES_REQUESTED** [review]
Project did not get created when 
- Mac
- Tested on [dataset](https://drive.google.com/drive/folders/1dTvbIz7NqI-b6R2em3AjPa_xnUYt3HaL)
- Start fresh on .classifai

Log : https://gist.github.com/codenamewei/2b4f11e42b196ca350d85491ada8aa98
UI after import 
Screenshot 2021-06-04 at 2 35 07 PM

Let me know if its something just on my system.

**Comment by YCCertifai** [comment]
@codenamewei the bug is fixed.

**Review by codenamewei — CHANGES_REQUESTED** [review]
Using this dataset [image_fail_display.zip](https://github.com/CertifaiAI/classifai/files/6611053/image_fail_display.zip)

log gist: [here](https://gist.github.com/codenamewei/4b6e893cc5c3b14845795e3be7f7be73)


1. Found a concern in general. When a data point is not supported, its saved to the database, checked and not loaded everytime. For example, if the image is webp and not supported at the current point, should it dont save in database in the first place? 
That way the tool dont need to check and failed to load the image everytime loading the project, which spend the computing time.

2. the message of log.info is printing alot of messages in the terminal when there's alot of project. Do we want to consider changing it to log.debug?
- there is concern of log.info and all the printing in terminal will actually slow down the performance of the tool (cause printing in terminal is always slower but this problem does not have in log.debug and log.warn cause it only writes to the file without printing it)
Example of log message in terminal when i have multiple projects: [here](https://gist.github.com/codenamewei/c1bf2491b2c1b4b2f3681cf6eaaaaea9)
- since end user wont see terminal if they install using package, printing it in terminal does not matters cause they dont see it. If want user to notice what is wrong, backend will have to send the error content to frontend to print it out as message prompt

**Comment by YCCertifai** [comment]
> Using this dataset [image_fail_display.zip](https://github.com/CertifaiAI/classifai/files/6611053/image_fail_display.zip)
> 
> log gist: [here](https://gist.github.com/codenamewei/4b6e893cc5c3b14845795e3be7f7be73)
> 
> 1. Found a concern in general. When a data point is not supported, its saved to the database, checked and not loaded everytime. For example, if the image is webp and not supported at the current point, should it dont save in database in the first place?
>    That way the tool dont need to check and failed to load the image everytime loading the project, which spend the computing time.
> 2. the message of log.info is printing alot of messages in the terminal when there's alot of project. Do we want to consider changing it to log.debug?
> 
> * there is concern of log.info and all the printing in terminal will actually slow down the performance of the tool (cause printing in terminal is always slower but this problem does not have in log.debug and log.warn cause it only writes to the file without printing it)
>   Example of log message in terminal when i have multiple projects: [here](https://gist.github.com/codenamewei/c1bf2491b2c1b4b2f3681cf6eaaaaea9)
> * since end user wont see terminal if they install using package, printing it in terminal does not matters cause they dont see it. If want user to notice what is wrong, backend will have to send the error content to frontend to print it out as message prompt

1. The invalid images is not saved in database. Instead, the logic during [metadata retrieval](https://github.com/CertifaiAI/classifai/blob/v2_alpha/classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioVerticle.java#L535-L554) always checks the project root path to get the number of images. 

2. From the point 1, we see that files checking always happens when metadata is retrieved, therefore there're alot image invalid messages.

3. Changing the log info message to log debug, did not solve users' concern when image is not loaded into classifai. Prompt it to frontend is a good idea if log debug is used.

Suggestion
1. Change log.info to log.debug + frontend promt message -> to tell user which images is not imported and why it is not imported.
2. Keep the metadata retrieval logic first since we do not want to cause any potential logic breaking. And keep this in note to change the image number retrieval logic in the next bug fix / version release

**Comment by codenamewei** [comment]
> > Using this dataset [image_fail_display.zip](https://github.com/CertifaiAI/classifai/files/6611053/image_fail_display.zip)
> > log gist: [here](https://gist.github.com/codenamewei/4b6e893cc5c3b14845795e3be7f7be73)
> > 
> > 1. Found a concern in general. When a data point is not supported, its saved to the database, checked and not loaded everytime. For example, if the image is webp and not supported at the current point, should it dont save in database in the first place?
> >    That way the tool dont need to check and failed to load the image everytime loading the project, which spend the computing time.
> > 2. the message of log.info is printing alot of messages in the terminal when there's alot of project. Do we want to consider changing it to log.debug?
> > 
> > 
> > * there is concern of log.info and all the printing in terminal will actually slow down the performance of the tool (cause printing in terminal is always slower but this problem does not have in log.debug and log.warn cause it only writes to the file without printing it)
> >   Example of log message in terminal when i have multiple projects: [here](https://gist.github.com/codenamewei/c1bf2491b2c1b4b2f3681cf6eaaaaea9)
> > * since end user wont see terminal if they install using package, printing it in terminal does not matters cause they dont see it. If want user to notice what is wrong, backend will have to send the error content to frontend to print it out as message prompt
> >   @codenamewei
> 
> 1. The invalid images is not saved in database. Instead, the logic during [metadata retrieval](https://github.com/CertifaiAI/classifai/blob/v2_alpha/classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioVerticle.java#L535-L554) always checks and loops through the project root path to get the number of images.
> 2. From the point 1, we see that files checking always happens when metadata is retrieved, therefore there're alot image invalid messages.
> 3. Changing the log info message to log debug, did not solve users' concern when image is not loaded into classifai. Prompt it to frontend is a good idea if log debug is used.
> 
> Suggestion
> 
> 1. Change log.info to log.debug + frontend promt message -> to tell user which images is not imported and why it is not imported.
> 2. Keep the metadata retrieval logic first since we do not want to cause any potential logic breaking. And keep this in note to change the image number retrieval logic in the next bug fix / version release

i agree with the suggestion. kindly work on the details..

**Comment by YCCertifai** [comment]
Will open another pull request as the frontend has changed.

**Pull request closed without merging**
