### PR TITLE
Create Project Workflow Refactored

### PR DESCRIPTION
**Pull request by codenamewei**
# Description

Check this PR for elaborative explanation
https://github.com/CertifaiAI/Classifai_FrontEnd/pull/166

do thorough checking on 
1. Create new project
    - with label file / without label file
    - with recursive child folder / without recursive child folder
2. Import project
   - with label file / without label file
   - with recursive child folder / without recursive child folder
3. Reload project
   - Plus new images
   - Delete existing images
   - Rename some images in the same folder 

See if all these scenarios works fine @ken479 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [x] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged
- [x] CHANGELOG.md has been updated.

### CODE REVIEW

**Comment by codenamewei** [comment]
https://gist.github.com/codenamewei/19451f379a5efe29edab3c64c0a7c879

API changes map to this branch for your references

its not exactly well documented for now, but better than nothing

@ken479 when this branch being merged, will need you to reflect it in gitbook documentation too thank you


cc @devenyantis @YCCertifai

**Comment by ken479** [comment]
1) Tested with no issue on create project (label/ without label) and (with recursive child folder/ no recursive child folder) 
2) Tested with no issue on import project. However, labels have issue
3) Tested with large dataset with no issue on import into classifai
4) Have problem in project reload

**Review by ken479 — APPROVED** [review]

**Comment by devenyantis** [comment]
> 1. Tested with no issue on create project (label/ without label) and (with recursive child folder/ no recursive child folder)
> 2. Tested with no issue on import project. However, labels have issue
> 3. Tested with large dataset with no issue on import into classifai
> 4. Have problem in project reload

Maybe can double check with 3 projects. See if there are any side effects.

**Comment by codenamewei** [comment]
> https://gist.github.com/codenamewei/19451f379a5efe29edab3c64c0a7c879
> 
> API changes map to this branch for your references
> 
> its not exactly well documented for now, but better than nothing
> 
> @ken479 when this branch being merged, will need you to reflect it in gitbook documentation too thank you
> 
> cc @devenyantis @YCCertifai

@ken479 will need you to work on documentation in your current gitbook branch too

**Pull request merged**
