### PR TITLE
Sum v2a folder file validation

### PR DESCRIPTION
**Pull request by YCCertifai**
# Description
## Bug fixing PR
Frontend required: https://github.com/CertifaiAI/Classifai_FrontEnd/tree/alpha1_fileValidation
## Project Root Path Missing
Previously user will be stuck at loading page when a project root path is missing. #393 

Now, the problem is solved. And a "Invalid Path" tag will be assigned to inform user
image

## Invalid Image Fix
[Dataset](https://drive.google.com/drive/folders/1dTvbIz7NqI-b6R2em3AjPa_xnUYt3HaL?usp=sharing)

### Incorrect Image Number 
Previously ClassifAI will include the invalid images in the total number of images #395 

Now, the problem is solved. And the invalid images will be downloaded as a txt file, and a prompt message will inform user to convert it to any supported image type

image
image

# Documentation Changes
- [gitbook](https://app.gitbook.com/@skymind/s/classifai/~/drafts/-McRZDFfs5qkaU2CJFvw/v/dev/development/rest-api/v1/@drafts): pending to merge
- CHANGELOG.md not changed for current fix as it is a fix current developing feature, autopr is added for past pr

Fixes # (issue)

#393 #395
## Type of change

Please delete options that are not relevant.

- [x] Bug fix (Non-breaking change which fixes an issue)
- [ ] New feature (Non-breaking change which adds functionality)
- [ ] Breaking change (Fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update (Example: REST API changes)

# Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged
- [x] CHANGELOG.md has been updated
- [x] Update [Gitbook REST API Page](https://docs.classifai.ai/v/dev/development/rest-api)

### CODE REVIEW

**Comment by codenamewei** [comment]
@YCCertifai 

can we 
1. get compiled code from https://github.com/CertifaiAI/Classifai_FrontEnd/tree/alpha1_fileValidation to this branch?
2. @devenyantis  and i check this branch 
3. if things go well we approve https://github.com/CertifaiAI/Classifai_FrontEnd/pull/176
4. when (3) is merged to frontend main branch, we come back to approve this PR to merge to v2_alpha

**Comment by devenyantis** [comment]
> @YCCertifai
> 
> can we
> 
> 1. get compiled code from https://github.com/CertifaiAI/Classifai_FrontEnd/tree/alpha1_fileValidation to this branch?
> 2. @devenyantis  and i check this branch
> 3. if things go well we approve [CertifaiAI/Classifai_FrontEnd#176](https://github.com/CertifaiAI/Classifai_FrontEnd/pull/176)
> 4. when (3) is merged to frontend main branch, we come back to approve this PR to merge to v2_alpha

After 4, I will submit pr for 

- backend: https://github.com/CertifaiAI/classifai/tree/deven_addExportStatus

Have checked with Amal.

- https://github.com/CertifaiAI/Classifai_FrontEnd/tree/amal_exportstatus

**Comment by YCCertifai** [comment]
@codenamewei  @devenyantis updated

**Comment by codenamewei** [comment]
merged gitbook changes

**Comment by devenyantis** [comment]
@codenamewei Working on Windows

Invalid project path
Capture2

Invalid images
Capture3

**Comment by codenamewei** [comment]
> @codenamewei Working on Windows
> 
> Invalid project path
> Capture2
> 
> Invalid images
> Capture3

got it

**Comment by codenamewei** [comment]
@YCCertifai @amalsyahmi-certifai 

Screenshot 2021-06-18 at 10 18 41 AM

**Comment by YCCertifai** [comment]
@codenamewei @devenyantis you might encounter some problem with the build frontend just now,
now it's solved...
@amalsyahmi-certifai this frontend is not updated to the current v2_alpha
image

**Comment by codenamewei** [comment]
> @YCCertifai @amalsyahmi-certifai
> 
> Screenshot 2021-06-18 at 10 18 41 AM

i've rebuild this from frontend branch, cause just a while ago the merge from v2_alpha is getting the old ui

**Review by codenamewei — CHANGES_REQUESTED** [review]
comments attached on others

**Review by devenyantis — APPROVED** [review]

**Comment by codenamewei** [comment]
on it

**Comment by YCCertifai** [comment]
@codenamewei @devenyantis 
- Frontend is updated to the latest v2alpha
- Multiple tags problem is solved
- Invalid Path project is not allowed to open
- Project Path are shown

**Review by codenamewei — APPROVED** [review]
perfect

**Pull request merged**
