### PR TITLE
🚀 Change alpha1 to alpha2

### PR DESCRIPTION
**Pull request by devenyantis**
# Description

Change alpha1 to alpha2

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (Non-breaking change which fixes an issue)
- [ ] New feature (Non-breaking change which adds functionality)
- [ ] Breaking change (Fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update (Example: REST API changes)

# Tested on?

- [ ] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged
- [ ] CHANGELOG.md has been updated
- [ ] Update [Gitbook REST API Page](https://docs.classifai.ai/v/dev/development/rest-api)

### CODE REVIEW

**Comment by yinchuangsum** [comment]
there are few files are not changed:
1. https://github.com/CertifaiAI/classifai/blob/deven_change_alpha2/classifai-test/pom.xml#L23
2. https://github.com/CertifaiAI/classifai/blob/deven_change_alpha2/startClassifai.sh#L3

**Comment by yinchuangsum** [comment]
there are some part requires changes in frontend too 
image

**Comment by devenyantis** [comment]
> there are some part requires changes in frontend too
> image

This is UI related. Will do this separate pr with the welcome launcher.

**Comment by yinchuangsum** [comment]
> > there are some part requires changes in frontend too
> > image
> 
> This is UI related. Will do this separate pr with the welcome launcher.

ah okay...

**Review by yinchuangsum — APPROVED** [review]
LGTM

**Pull request merged**
