### PR TITLE
Solving out of memory error when exporting project

### PR DESCRIPTION
**Pull request by devenyantis**
# Description

When exporting project with data, OOM will occur

**What change**
- Changing the way putting file into zip file. Before, the output stream is kept opened and loop to insert data. This cause the stream to be very huge as they accumulate in the memory. The fix. Zip file opened and closed after every loop. So, they won't accumulate until the end.
- Initial memory heap size. The default value is 256mb. Changed to 1Gb. In every loop, program at least need heap memory to hold function arguments and local variable. Something like ProjectLoader and BufferedImage is huge for memory. If in the current loop, the program process a big image, it will quickly run out of heap memory. Increasing to 1Gb is only based on my set of images. **Note: Setting 1Gb heap size does not mean the program will utilize fully.** 

All fixes are for OOM error only. 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Tested on?

- [X] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Review by YCCertifai — CHANGES_REQUESTED** [review]
1. This branch is not pulled from the latest v2_alpha
2. -Xmx is the configuration for maximum heap size...
 referring to 
image
and 
image

users are expected to have at least 1Gb maximum heap size. In my case, my pc has 16Gb RAM, it will have 4Gb max heap by default. Explicitly state the maximum heap size will cause reduction of max heap size...

**Comment by devenyantis** [comment]
@YCCertifai @codenamewei 

For the heap size, the default value depends based on OS. On Windows, the default is 268435456b which is around 268mb. Look at MaxHeapSize.
Capture8

 Even if I view from JConsole, the default is around 256mb. Look at Max.

Capture7

So, for this reason, specifying is better. 

I'm fine with more than 1Gb. According to my reading, it is quite standard nowadays for java software. If we specify that users must have 8Gb physical ram to use classifai, then we can specify 4Gb to be safe.

**Comment by codenamewei** [comment]
suggest go with -Xmx2048m for now. 

i still see people using 4GB Ram of Computer with Classifai, just want to make sure they still stands a chance....

**Comment by YCCertifai** [comment]
https://www.eclipse.org/openj9/docs/xxinitialrampercentage/

@devenyantis perhaps we can set the max heap size based on percentage instead of a fixed value. I would suggest 25% is a good value as 4Gb of RAM is our minimum requirement, so we can get at least 1Gb of the max heap size...

**Comment by devenyantis** [comment]
@codenamewei @YCCertifai 

Found out, the default value is capped because of java bit. 

I installed Java through intellij. Although intellij is 64 bit, it install 32 bit openjdk-14 to my system. 

- Java 32 bit cause the system to set default max to 256mb. Max is 2Gb. If user specify more than that, heap allocation error will happen.

After changing Java, my default value is 5Gb heap size. 

On a side note, anyone that install Java the same way probably cannot run classifai.

**Comment by devenyantis** [comment]
> https://www.eclipse.org/openj9/docs/xxinitialrampercentage/
> 
> @devenyantis perhaps we can set the max heap size based on percentage instead of a fixed value. I would suggest 25% is a good value as 4Gb of RAM is our minimum requirement, so we can get at least 1Gb of the max heap size...
> 
> image
> image
> I've tested this on my side, it's working....

Probably will work on my side as well. As mentioned in previous comment, it is because of java bit. 

For 32 bit, anything above 1.8-2Gb will definitely fail.

**Comment by codenamewei** [comment]
@devenyantis 

yep but i dont think it is a big concern for end user, 

cause we package classifai for release, we supposedly package the right version of java with classifai


side note : classifai does not use build-in java but java come along with classifai installation

**Review by YCCertifai — APPROVED** [review]

**Review by YCCertifai — CHANGES_REQUESTED** [review]
@devenyantis 
Almost forget about it...
Remember to merge with the latest v2_alpha branch...

**Comment by devenyantis** [comment]
> @devenyantis
> Almost forget about it...
> Remember to merge with the latest v2_alpha branch...

Done. Merged before commit the latest revert.

**Comment by YCCertifai** [comment]
> > @devenyantis
> > Almost forget about it...
> > Remember to merge with the latest v2_alpha branch...
> 
> Done. Merged before commit the latest revert.

ah.. okok

**Review by codenamewei — APPROVED** [review]

**Pull request merged**
