### PR TITLE
🐛 Deven fix missing rename

### LINKED ISSUE #468: Rename Image API endpoint not found
**Describe the bug**
Rename image function not working. Response from backend is 404 not found.

**To Reproduce**
1. Go to any existing bounding box project
2. Click on rename icon at any image
3. Enter image name and click proceed
4. See error in dev tools console

**Expected behavior**
Expect rename function working correctly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by devenyantis**
# Description

Somehow, rename api is missing, this PR is adding back reverted commit to v2_alpha. 

Fixes #468 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (Non-breaking change which fixes an issue)
- [ ] New feature (Non-breaking change which adds functionality)
- [ ] Breaking change (Fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update (Example: REST API changes)

# Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged
- [ ] CHANGELOG.md has been updated
- [ ] Update [Gitbook REST API Page](https://docs.classifai.ai/v/dev/development/rest-api)

### CODE REVIEW

**Comment by devenyantis** [comment]
Code analysis failing is caused by duplicated lines in BoundingBoxVerticle and SegVerticle. 
Not possible to fix for now since the code needs to be copy and paste to provide functionality for both

**Comment by codenamewei** [comment]
> Code analysis failing is caused by duplicated lines in BoundingBoxVerticle and SegVerticle.
> Not possible to fix for now since the code needs to be copy and paste to provide functionality for both

yep , will disregard that...
and come back to merge this once Amal approves it.

**Review by amalsyahmi-certifai — APPROVED** [review]
Working as expected.

**Review by codenamewei — APPROVED** [review]
Thanks for the quick fix.

**Pull request merged**
