### PR TITLE
♻️ Remove event bus

### PR DESCRIPTION
**Pull request by devenyantis**
# Description

Removing usage of event bus

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (Non-breaking change which fixes an issue)
- [x] New feature (Non-breaking change which adds functionality)
- [x] Breaking change (Fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update (Example: REST API changes)

# Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged
- [ ] CHANGELOG.md has been updated
- [ ] Update [Gitbook REST API Page](https://docs.classifai.ai/v/dev/development/rest-api)

### CODE REVIEW

**Comment by devenyantis** [comment]
The unsuccessful check is caused by code duplication. Happen because I cope the chunks from verticle directly to portfoliodb

**Comment by yipkhenlai** [comment]
Hi @devenyantis, I tested that when create project or import project, images will be loaded twice. Please check whether you meet the same issue. 

Other functionalities are good.  Thanks.

chrome_Qkt30idpgC

**Comment by devenyantis** [comment]
> Hi @devenyantis, I tested that when create project or import project, images will be loaded twice. Please check whether you meet the same issue.
> 
> Other functionalities are good. Thanks.
> 
> chrome_Qkt30idpgC

It doesn't happen on my side. Can you upload the dataset folder to google drive and send to me.

**Comment by yipkhenlai** [comment]
> > Hi @devenyantis, I tested that when create project or import project, images will be loaded twice. Please check whether you meet the same issue.
> > Other functionalities are good. Thanks.
> > chrome_Qkt30idpgC
> 
> It doesn't happen on my side. Can you upload the dataset folder to google drive and send to me.

Hi @devenyantis, sure

**Review by yipkhenlai — APPROVED** [review]

**Review by treo — APPROVED** [review]

**Pull request merged**
