### PR TITLE
Adding automatic PR creation workflow

### PR DESCRIPTION
**Pull request by fariskamaludin-skymind**
# Description

- Adding automatic PR creation capability once copy paste [workflow][1] from Classifai_FrontEnd is triggered
- Adding this workflow will ease the process in syncing up between [dist folder][2] & [webroot folder][3]

[1]: https://github.com/CertifaiAI/Classifai_FrontEnd/blob/faris_added_copypaste_workflow/.github/workflows/copy.yml
[2]: https://github.com/CertifaiAI/Classifai_FrontEnd/tree/main/dist/classifai
[3]: https://github.com/CertifaiAI/classifai/tree/v2_alpha/classifai-core/src/main/resources/webroot

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [X] Adding GitHub Action workflow

# Tested on?

- [ ] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [X] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged
- [ ] CHANGELOG.md has been updated.

### CODE REVIEW

**Comment by codenamewei** [comment]
@fariskamaludin-skymind 
to initiate this, does it mean when new PR from any branch to main branch in Classifai_Frontend happens and have changes in Classifai_frontend/dist , then github actions will push into this repo while renaming it as webroot?

**Comment by fariskamaludin-skymind** [comment]
> @fariskamaludin-skymind
> to initiate this, does it mean when new PR from any branch to main branch in Classifai_Frontend happens and have changes in Classifai_frontend/dist , then github actions will push into this repo while renaming it as webroot?

Exactly, the process workflows are as follow:

1) New PR from any branch tries to merge with the main from Classifai_Frontend and only if it have changes in Classifai_frontend/dist/classifai , it will trigger the [copy workflow](https://github.com/CertifaiAI/Classifai_FrontEnd/blob/faris_added_copypaste_workflow/.github/workflows/copy.yml) from that repo.

2) The destination of pasting into this repo, classifai, would be at branch **faris_auto_pr**. If it does not exist, github action will automatically create it, cloning it from the base branch, which is **v2_alpha**. Moreover, it paste directly into the [webroot folder](https://github.com/CertifaiAI/classifai/tree/v2_alpha/classifai-core/src/main/resources/webroot). However, it delete everything in the webroot folder first prior pasting into it. 

3) Due to the action of pushing the codes into faris_auto_pr branch, only then this auto pr workflow will trigger. Thus, creating the PR, ready for merging with the default branch once approved.

Hope it answer your question.

**Comment by codenamewei** [comment]
> > @fariskamaludin-skymind
> > to initiate this, does it mean when new PR from any branch to main branch in Classifai_Frontend happens and have changes in Classifai_frontend/dist , then github actions will push into this repo while renaming it as webroot?
> 
> Exactly, the process workflows are as follow:
> 
> 1. New PR from any branch tries to merge with the main from Classifai_Frontend and only if it have changes in Classifai_frontend/dist/classifai , it will trigger the [copy workflow](https://github.com/CertifaiAI/Classifai_FrontEnd/blob/faris_added_copypaste_workflow/.github/workflows/copy.yml) from that repo.
> 2. The destination of pasting into this repo, classifai, would be at branch **faris_auto_pr**. If it does not exist, github action will automatically create it, cloning it from the base branch, which is **v2_alpha**. Moreover, it paste directly into the [webroot folder](https://github.com/CertifaiAI/classifai/tree/v2_alpha/classifai-core/src/main/resources/webroot). However, it delete everything in the webroot folder first prior pasting into it.
> 3. Due to the action of pushing the codes into faris_auto_pr branch, only then this auto pr workflow will trigger. Thus, creating the PR, ready for merging with the default branch once approved.
> 
> Hope it answer your question.

thats great...also like how we are removing the content in webroot folder first before putting the content in, which is the way we do it now.

**Review by codenamewei — APPROVED** [review]
Lets merge this and test this extensively for a few rounds.

If any enhancement. / problem arise, we'll only able to identify by then.

Good work @fariskamaludin-skymind

**Comment by fariskamaludin-skymind** [comment]
Noted on that, thank you @codenamewei

**Pull request merged**
