### PR TITLE
Copying and pasting dist folder's contents from Classifai_FrontEnd to classifai's webroot

### PR DESCRIPTION
**Pull request by fariskamaludin-skymind**
## This is an automatically created PR :robot::robot:

- It will triggered once codes in [***dist folder***][3] from repo [***Classifai_FrontEnd***][1] has been pushed.
- Files & sub-folder in [***dist folder***][3] of repo [***Classifai_FrontEnd***][1] will be copied into [***classifai's webroot***][2]
- Committed frontend PR's URL can be found in the commit history below.

[1]: https://github.com/CertifaiAI/Classifai_FrontEnd
[2]: https://github.com/CertifaiAI/classifai/tree/v2_alpha/classifai-core/src/main/resources/webroot
[3]: https://github.com/CertifaiAI/Classifai_FrontEnd/tree/main/dist/classifai

### CODE REVIEW

**Review by codenamewei — CHANGES_REQUESTED** [review]
The compiled code did not reflect changes in [#201](CertifaiAI/Classifai_FrontEnd#201) on my side

Example:
- No guiding cross line
Screenshot 2021-07-30 at 7 46 01 PM


Commit details
Screenshot 2021-07-30 at 7 43 08 PM

**Comment by fariskamaludin-skymind** [comment]
> The compiled code did not reflect changes in [#201](CertifaiAI/Classifai_FrontEnd#201) on my side
> 
> Example:
> 
> * No guiding cross line
> 
> Screenshot 2021-07-30 at 7 46 01 PM
> 
> Commit details
> Screenshot 2021-07-30 at 7 43 08 PM

@codenamewei I think you need to turn on the toggle button first

https://user-images.githubusercontent.com/83570177/127662784-2aa9a2b3-0d82-4f27-a120-f1025579ffca.mp4

**Comment by codenamewei** [comment]
> > The compiled code did not reflect changes in [#201](CertifaiAI/Classifai_FrontEnd#201) on my side
> > Example:
> > 
> > * No guiding cross line
> > 
> > Screenshot 2021-07-30 at 7 46 01 PM
> > Commit details
> > Screenshot 2021-07-30 at 7 43 08 PM
> 
> @codenamewei I think you need to turn on the toggle button first
> 
>  classifai.mp4

yep. missed that. working awesome!

**Review by codenamewei — APPROVED** [review]
Modified changelog. 
Also all the items in [#201](https://github.com/CertifaiAI/Classifai_FrontEnd/pull/201) works as intended.

**Review by devenyantis — APPROVED** [review]

**Pull request merged**
