### PR TITLE
update pascalVOC issue

### PR DESCRIPTION
**Pull request by BobbyLCW**
# Description
remove _format.xml for pascal VOC.

Fixes # (issue)
-
## Type of change
frontend code
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Comment by codenamewei** [comment]
changes are good for pascal voc ..

can do the same for yolo? to keep it consistent 

Screenshot 2021-01-21 at 8 52 52 PM


thank you @BobbyLCW

**Review by codenamewei — CHANGES_REQUESTED** [review]
Change on YOLO too thanks.

**Comment by BobbyLCW** [comment]
Updated and please validate thanks.

**Review by codenamewei — APPROVED** [review]
works fine now thanks.

**Pull request merged**
