### PR TITLE
✨ Build project and Import project using command line Interface

### PR DESCRIPTION
**Pull request by yipkhenlai**
# Description

Adding new feature build and import project using command line interface. This feature can be used as usual (create a new project and import project configuration file in Classifai) and in the Docker environment. The command line arguments are shown as follow:

**Building project with and without label list:**

1. java -jar classifai-uberjar-dev.jar --port=9999 --docker --projectname=demo --projecttype=segmentation 
   --datapath=/Users/john/Desktop/sample-image

2. java -jar classifai-uberjar-dev.jar --port=9999 --docker --projectname=demo --projecttype=segmentation 
   --datapath=/Users/john/Desktop/sample-image --labelpath=/Users/john/Desktop/sample-image/sample-label.txt 

**Import project configuration file**
1. java -jar classifai-uberjar-dev.jar --port=9999 --docker  --datapath=/Users/chia wei/Desktop/sample-image 
   --configpath=/Users/chia wei/Desktop/sample-image/sample-config.json

**Build and Import project in Docker environment:**

Move the attached Docker file into classifai-uberjar/target and perform build and run docker from here. The arguments in the docker file are free to modify and according to the command line argument above. startDocker.bat and startDocker.sh file are provided.

Two important volumes to be mount such as shared folder ( -v C:\Users\ken\Desktop\Image:/usr/Image) and database (-v C:\Users\ken\.classifai:/root/.classifai)

Please delete options that are not relevant.

- [x] Bug fix (Non-breaking change which fixes an issue)
- [x] New feature (Non-breaking change which adds functionality)

# Tested on?

- [x] Windows  
- [x] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged
- [x] CHANGELOG.md has been updated
- [ ] Update [Gitbook REST API Page](https://docs.classifai.ai/v/dev/development/rest-api)

### CODE REVIEW

**Comment by devenyantis** [comment]
@ken479 

Not sure if all these only happens on my machine.

1. When create project with existing names, the process shows name exists but did not exit program. Running in headless mode is hard to send sigint/sigkill to stop a process. So, need to make the program stop automatically for this.
2. When starting a project with data path containing exported project zip file, the program will load data twice.
Capture
4. Can't export project. The UI is stucked at loading
5. I think it is better to include warnings message and exit directly if user enter wrong format of config
6. Can't import project from config

https://user-images.githubusercontent.com/69179469/130718039-d4182944-f3ca-43d0-9590-1323c34c7ca5.mp4

Haven't test docker yet. Will try it after bug above are fixed.

**Comment by yipkhenlai** [comment]
> @ken479
> 
> Not sure if all these only happens on my machine.
> 
> 1. When create project with existing names, the process shows name exists but did not exit program. Running in headless mode is hard to send sigint/sigkill to stop a process. So, need to make the program stop automatically for this.
> 2. When starting a project with data path containing exported project zip file, the program will load data twice.
>    Capture
> 3. Can't export project. The UI is stucked at loading
> 4. I think it is better to include warnings message and exit directly if user enter wrong format of config
> 5. Can't import project from config
> 
>  unable_to_import_project.mp4 
> Haven't test docker yet. Will try it after bug above are fixed.

Thank you @devenyantis for pointing out the problems, I will look into it and get back to you shortly.

**Comment by yipkhenlai** [comment]
> @ken479
> 
> Not sure if all these only happens on my machine.
> 
> 1. When create project with existing names, the process shows name exists but did not exit program. Running in headless mode is hard to send sigint/sigkill to stop a process. So, need to make the program stop automatically for this.
> 2. When starting a project with data path containing exported project zip file, the program will load data twice.
>    Capture
> 3. Can't export project. The UI is stucked at loading
> 4. I think it is better to include warnings message and exit directly if user enter wrong format of config
> 5. Can't import project from config
> 
>  unable_to_import_project.mp4 
> Haven't test docker yet. Will try it after bug above are fixed.

Hi @devenyantis @codenamewei, here are some updates I have made 
Thank you for your review, Deven
1. Agree on that, I have added on condition to terminate the app when detected existing project name
2. I have tested the dataset folder with zip file, the image is loaded once. I will keep an eye on this issue, if happen I will notify you all.
3. I didn't encounter this problem on my machine
4. Agree on that. I have added on checking the config file format before it loads to the app
5. This is when the user imports a similar project as in the database, so it will reload the project from the database. If there is no similar project, it will load successfully. Sorry for the lack of information, I have added more log info to it.

**Comment by yipkhenlai** [comment]
@devenyantis this branch is with obsolete backend, thereby this PR is closed.

**Pull request closed without merging**
