### PR TITLE
Copying and pasting dist folder's contents from Classifai_FrontEnd to classifai's webroot

### PR DESCRIPTION
**Pull request by fariskamaludin-skymind**
## This is an automatically created PR :robot::robot:

- It will triggered once codes in [***dist folder***][3] from repo [***Classifai_FrontEnd***][1] has been pushed.
- Files & sub-folder in [***dist folder***][3] of repo [***Classifai_FrontEnd***][1] will be copied into [***classifai's webroot***][2]
- Committed frontend PR's URL can be found in the commit history below.

[1]: https://github.com/CertifaiAI/Classifai_FrontEnd
[2]: https://github.com/CertifaiAI/classifai/tree/v2_alpha/classifai-core/src/main/resources/webroot
[3]: https://github.com/CertifaiAI/Classifai_FrontEnd/tree/main/dist/classifai

### CODE REVIEW

**Comment by devenyantis** [comment]
Don't know if this is caused by this change, but the import window doesn't pop up. 
In v2_alpha, import works.

**Comment by codenamewei** [comment]
@devenyantis hmmm maybe can verify by doing a fresh build from classifai_frontend and see if the same scenario persists.

**Comment by amalsyahmi-certifai** [comment]
@devenyantis It's because the PR #441 does not merged yet

**Comment by devenyantis** [comment]
@amalsyahmi-certifai @codenamewei 

Okay. In that case, should we rebase to #441 ?

And. Is there any backend dependencies for the sorting? 
I tested this pr yesterday, it shows July 4 for both created and modified. Today it shows July 5. Haven't open any project. 

In alpha1, the created dates are correctly shown.

**Comment by codenamewei** [comment]
thanks for the clarification , ill rebase this frontend to #441 

and let deven review and possibly merge #441 

then we'll come back to delete feature

ill do it now.

**Review by codenamewei — COMMENTED** [review]
works

**Pull request merged**
